project:
  type: book
  
book:
  title: "Thesis Proposal: Modeling Crustacean Morphometric Maturity"
  author: "Ruby Krasnow"
  repo-url: https://github.com/rmk118/thesis_proposal
  back-to-top-navigation: true
  page-navigation: true
  favicon: figures/simple_crab.svg
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
      - introduction/intro.qmd
      - introduction/importance.qmd
      - introduction/valuable_species.qmd
    - part: "Systematic Review"
      chapters:
      - syst_review/systematic_review.qmd
    - eco_evo.qmd
    - part: "Simulation Testing"
      chapters:
      - simulations/simulation_testing.qmd
      - simulations/planned_sims.qmd
    - morphmat.qmd
    - jonah.qmd
  appendices:
    - data_mgmt.qmd
    - syst_review/eml.qmd
    - syst_review/supporting_tabs.qmd
 
bibliography: references.bib
number-depth: 3
toc-depth: 2
toc-expand: 1
format:
  html:
    theme: cosmo
    code-link: true
    
execute:
  echo: false
  freeze: auto
link-external-newwindow: true 
editor_options: 
  chunk_output_type: console