project:
  type: book
  
book:
  title: "Thesis Proposal: Modeling Crustacean Morphometric Maturity"
  author: "Ruby Krasnow"
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
      - importance.qmd
      - valuable_species.qmd
    - systematic_review.qmd
    - eco_evo.qmd
    - simulation_testing.qmd
    - morphmat.qmd
    - jonah.qmd
 
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt
    
execute:
  echo: false
  freeze: auto
link-external-newwindow: true 
editor_options: 
  chunk_output_type: console