project:
  type: book
  
book:
  title: "Thesis Proposal: Modeling Crustacean Morphometric Maturity"
  author: "Ruby Krasnow"
  repo-url: https://github.com/rmk118/thesis_proposal
  back-to-top-navigation: true
  page-navigation: true
  favicon: figures/simple_crab.svg
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
      - intro.qmd
      - importance.qmd
      - valuable_species.qmd
    - systematic_review.qmd
    - eco_evo.qmd
    - simulation_testing.qmd
    - morphmat.qmd
    - jonah.qmd
  appendices:
    - data_mgmt.qmd
    - eml.qmd
 
bibliography: references.bib
number-depth: 3
toc-depth: 2
toc-expand: 1
format:
  html:
    theme: cosmo
    code-link: true
    
execute:
  echo: false
  freeze: auto
link-external-newwindow: true 
editor_options: 
  chunk_output_type: console