---
title: "eml"
format: html
---

# Data extraction tables

## General extraction

+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **attributeName** | **class** | **attributeDefinition**                                                                                                                                                                                                                                                                                                                                                                                                           |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| authors           | character | Authors of the source, in the order in which they were listed in the source. Author names should be in Last, First M.I. format (e.g., Smith, John L.) with initials used if first names are not provided (Smith, J. or Smith, J.L.). Separate author names with a semicolon and do not include "and" or an ampersand symbol before the last author in the list.                                                                   |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| auth_short        | character | First author of source if there are 3+ authors or "Auth1 & Auth2" if there are only two authors.                                                                                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| type              | character | Source type (journal article, thesis, conference paper, etc.)                                                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| title             | character | Source title, in sentence case.                                                                                                                                                                                                                                                                                                                                                                                                   |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| paper_link        | character | Link to paper, using a DOI or other permanent identifier where available.                                                                                                                                                                                                                                                                                                                                                         |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| language          | character | Language(s) in which the source was published                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| journal           | character | Journal title, if applicable. Do not abbreviate.                                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| species_common    | character | Common name of modeled species, either as given in the source document or as listed in WoRMS.                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| species_sci       | character | Scientific name of modeled species (ITIS standard/most current valid taxonomic name, as listed in WoRMS)                                                                                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| country           | character | Country or countries where the samples were collected. This is not necessarily the country home to the institution(s) with which the authors are primarily affiliated. Refer to this link for standardized country names: <https://en.wikipedia.org/wiki/List_of_sovereign_states>                                                                                                                                                |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time_method       | character | Description of how temporal variation was included in the study (e.g., separate estimates of SM50 for multiple years of data vs. dynamical system/state-space approach).                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| spatial_method    | character | Description of how spatial variation was included in the study (e.g., separate estimates of SM50 for multiple regions vs. a spatially-explicit model).                                                                                                                                                                                                                                                                            |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| all_vars_meas     | character | List of all variables measured in the study for the purpose of determining size at maturity. Use standardized measurement names where possible.                                                                                                                                                                                                                                                                                   |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| all_vars_used     | character | List of all variables used to obtain the final estimate of SM50. Most commonly carapace width and chela height for males and carapace width and abdomen width or length for females. Use standardized measurement names where possible.                                                                                                                                                                                           |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ref_var           | character | Which reference variable was used as a measure of body size? Use standardized measurement names where possible.                                                                                                                                                                                                                                                                                                                   |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| claw_regen_notes  | character | Description of approach used to exclude regenerating chelae from the final analysis.                                                                                                                                                                                                                                                                                                                                              |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| mod_form          | character | Modeling approach used to estimate SM50. Used standardized names where possible.                                                                                                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| referred_to_as    | character | Authors' name for the modeling approach used to estimate SM50.                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| reference         | character | Which paper did the authors cite as a reference for their modeling approach?                                                                                                                                                                                                                                                                                                                                                      |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| error_dist        | character | Did the authors mention error distributions? If true, explain: did they explicitly model error distributions or structures (measurement error, heteroscedasticity, etc.) and if so, how?                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| reg_type          | character | Provide details on the type of regression did the authors use, if the answer was TRUE for "Did the authors discuss/justify their use of Model I vs Model II regression?"                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| mod_tests         | character | What kinds of tests, if any, did the authors perform on the results of their model? This can include the type of test used to compare the SM50 to a linear model                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ref_var_notes     | character | Notes about justification for selecting the given reference variable.                                                                                                                                                                                                                                                                                                                                                             |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| software          | character | What software or programming language was used for the modeling?                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| package           | character | Any specific computer programs, scripts, orcpackages described by the source as being used for the model.                                                                                                                                                                                                                                                                                                                         |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| code_link         | character | Link to code, using a DOI or other permanent identifier where available.                                                                                                                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| data_link         | character | Link to data, using a DOI or other permanent identifier where available.                                                                                                                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ecoevo_sig        | character | Paper's explanation of the evolutionary/ecological significance of the change in chela and/or abdomen morphology at maturity.                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| fishing_effect    | character | Paper's findings related to the effects of harvesting on size at maturity.                                                                                                                                                                                                                                                                                                                                                        |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| temp_effect       | character | Paper's findings related to the effects of temperature or climate change on size at maturity.                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| comments          | character | Other comments about the paper                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| year              | dateTime  | Year of publication                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| start_date        | dateTime  | Beginning of time period during which samples were collected                                                                                                                                                                                                                                                                                                                                                                      |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| end_date          | dateTime  | End of time period during which samples were collected                                                                                                                                                                                                                                                                                                                                                                            |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| habitat           | factor    | Type of habitat where the crustacean lives ("marine", "fresh", "brackish", "terrestrial"). Default should be what is listed in WoRMS, unless the source document indicates otherwise. For example, if WoRMS lists a species as marine/freshwater/brackish but the population studied in the article was only from a freshwater stream, put "fresh".                                                                               |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sex               | factor    | Sex for which SM50 is being estimated (M, F, B = both separately, C = both combined, NS = not specified). Note that sometimes size at maturity will be estimated for both sexes but for females will be done using ovarian staging or similar physiological methods, while allometric data are used for males. If estimates of SM50 are not derived for the females besides a normal maturity ogive, this would only count as "M" |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| phys_comp         | factor    | How did the estimate of size at morphometric maturity compare to estimates of size at physiological or functional maturity, either from the same study or from previous studies mentioned in the paper?\                                                                                                                                                                                                                          |
|                   |           | higher/lower/same = morphometric L50 was higher than/lower than/roughly the same as phys/func L50\                                                                                                                                                                                                                                                                                                                                |
|                   |           | conflict = morphometric L50 was higher than some previous phys/func estimates and lower than others\                                                                                                                                                                                                                                                                                                                              |
|                   |           | NA if no comparison made                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| also_phys         | factor    | Did the authors also measure physiological or functional maturity? E.g., classification of gonad development, presence of sperm in female spermathecae. (TRUE/FALSE)                                                                                                                                                                                                                                                              |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| coords_avail      | factor    | Did the authors provide geographic coordinates for the location(s) where samples were collected? TRUE, FALSE, or APPROX if not provided but could be extracted from provided maps or closely approximated based on information given in the text                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time_var          | factor    | Did the authors consider temporal variation in SM50? (TRUE/FALSE)                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| spatial_var       | factor    | Did the authors consider spatial variation in SM50? (TRUE/FALSE)                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| claw_regen        | factor    | Did they mention excluding crabs with (fully or partially) regenerated chelae? (TRUE/FALSE)                                                                                                                                                                                                                                                                                                                                       |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| mult_models       | factor    | Did the authors test multiple modeling approaches to estimate SM50? Note: this does not include a simple linear model developed as the null hypothesis to a piecewise model (see next question). Also excluded are models based on morphological or functional maturity data. (TRUE/FALSE)                                                                                                                                        |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| reg_mention       | factor    | Did the authors discuss/justify their use of Model I vs Model II regression? (OLS, Reduced Major Axis, Major Axis) (TRUE/FALSE)                                                                                                                                                                                                                                                                                                   |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| log_trans         | factor    | Did the authors assume an untransformed or log-log relationship for the regression equation? NOTE that this does NOT refer to whether the authors used log-log data for the regression fitting or non-linear least squares (e.g., Levenberg-Marquardt), as either of those methods assume y=aX\^b instead of y=a+bx                                                                                                               |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| est_variance      | factor    | Did the study provide a measure of variance/confidence for their estimate of SM50? (SD, 95% CIs, etc.)                                                                                                                                                                                                                                                                                                                            |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| code_avail        | factor    | Does the paper provide the code used for the modeling? (TRUE/FALSE)                                                                                                                                                                                                                                                                                                                                                               |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| data_avail        | factor    | Does the paper provide the raw data used for the analysis? (TRUE/FALSE)                                                                                                                                                                                                                                                                                                                                                           |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| success           | factor    | Did the authors conclude that the morphometric relationship could be reliably used to estimate size at maturity, or at least to distinguish between immature and mature individuals? (TRUE/FALSE)                                                                                                                                                                                                                                 |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| mgmt_context      | factor    | Did the authors mention tangible ways in which fisheries regulations/management frameworks might be adjusted based on their findings? (TRUE/FALSE)                                                                                                                                                                                                                                                                                |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| novel_stats       | factor    | Does the paper develop a novel method or include commentary about an existing modeling method that should be tested/explored during the simulation testing? (TRUE/FALSE)                                                                                                                                                                                                                                                          |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| study_id          | numeric   | ID number assigned to each study for the purpose of aligning entries in different datasets                                                                                                                                                                                                                                                                                                                                        |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| AphiaID           | numeric   | WoRMS AphiaID                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tot_samp_size     | numeric   | Total number of unique crustaceans from which morphometric data were analyzed                                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| min_samp_size     | numeric   | Minimum sample size used to estimate size at maturity, if separate models were fit for different sexes, regions, etc.                                                                                                                                                                                                                                                                                                             |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| max_samp_size     | numeric   | Maximum sample size used to estimate size at maturity, if separate models were fit for different sexes, regions, etc.                                                                                                                                                                                                                                                                                                             |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude          | numeric   | Latitude value(s), in EPSG 4326/WGS84 format                                                                                                                                                                                                                                                                                                                                                                                      |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| longitude         | numeric   | Longitude value(s), in EPSG 4326/WGS84 format                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| num_breakpoints   | numeric   | How many transition points were estimated? Default is 1, the transition between immature and mature, but could be \>1 if used to differentiate instars                                                                                                                                                                                                                                                                            |
+-------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Parameters

|  |  |  |
|----|----|----|
| **attributeName** | **class** | **attributeDefinition** |
| study_id | numeric | ID number assigned to each study for the purpose of aligning entries in different datasets |
| auth_short | character | First author of source if there are 3+ authors or "Auth1 & Auth2" if there are only two authors. |
| year | dateTime | Year of publication |
| title | character | Source title, in sentence case. |
| paper_link | character | Link to paper, using a DOI or other permanent identifier where available. |
| species_sci | character | Scientific name of modeled species (ITIS standard/most current valid taxonomic name, as listed in WoRMS) |
| x_axis_units | character | Unit of the x-axis/independent variable in the regression for which slope & intercept parameters are being extracted |
| y_axis_units | character | Unit of the y-axis/dependent variable in the regression for which slope & intercept parameters are being extracted |
| sm50_units | numeric | Unit in which SM50 value was given |
| sm50_SE | numeric | Standard error of SM50 value, if provided |
| sm50_SD | numeric | Standard deviation of SM50 value, if provided |
| sm50 | numeric | Final SM50 value(s) estimated in the study, in the original units |
| samp_size | numeric | Sample size of the specific regression from which parameters are being extracted |
| f_ab_slope | factor | How did the allometric slope parameter (growth rate of the female abdomen compared to carapace width or length) change at maturity? Options: inc, dec, none (no change), NA (if not discussed or not relevant for that modeling approach). Variables are abdomen width and carapace width unless otherwise specified |
| m_claw_slope | factor | How did the allometric slope parameter (growth rate of the male claw compared to carapace width or length) change at maturity? Options: inc, dec, none (no change), NA |
| f_ab_int | factor | How did the allometric intercept parameter (relative size of the female abdomen compared to carapace width or length) change at maturity? Options: inc, dec, none (no change), NA |
| m_claw_int | factor | How did the allometric intercept parameter (relative size of the male claw compared to carapace width or length) change at maturity? Options: inc, dec, none (no change), NA |
| comments | character | Other comments about the paper |

## Factor codes

|  |  |  |
|----|----|----|
| **attributeName** | **code** | **definition** |
| also_phys | complex | Not equivocally true or false; see comments for additional information. |
| also_phys | FALSE | FALSE |
| also_phys | TRUE | TRUE |
| claw_regen | complex | Not equivocally true or false; see comments for additional information. |
| claw_regen | FALSE | FALSE |
| claw_regen | TRUE | TRUE |
| code_avail | complex | Not equivocally true or false; see comments for additional information. |
| code_avail | FALSE | FALSE |
| code_avail | TRUE | TRUE |
| coords_avail | complex | Not equivocally true or false; see comments for additional information. |
| coords_avail | FALSE | FALSE |
| coords_avail | TRUE | TRUE |
| data_avail | complex | Not equivocally true or false; see comments for additional information. |
| data_avail | FALSE | FALSE |
| data_avail | TRUE | TRUE |
| est_variance | complex | Not equivocally true or false; see comments for additional information. |
| est_variance | FALSE | FALSE |
| est_variance | TRUE | TRUE |
| habitat | brackish | Lives in environments with intermediate or fluctuating salinities, including estuaries and mangroves |
| habitat | fresh | Lives in freshwater environments |
| habitat | marine | Lives in marine environments |
| habitat | semi-terrestrial | Lives partially on land (or in non-submerged trees) and partially in an aquatic environment |
| habitat | terrestrial | Lives on land |
| log_trans | complex | Not equivocally true or false; see comments for additional information. |
| log_trans | FALSE | FALSE |
| log_trans | TRUE | TRUE |
| mgmt_context | complex | Not equivocally true or false; see comments for additional information. |
| mgmt_context | FALSE | FALSE |
| mgmt_context | TRUE | TRUE |
| morph_v_phys | conflict | Morphometric SM50 was higher than some functional/physiological SM50 values and lower than others. Other complex situations that do not fall into one of the other four categories can be labeled as this and expanded upon in the comments column. |
| morph_v_phys | higher | Morphometric SM50 was higher than values provided for SM50 based on a measure of physiological or functional maturity. |
| morph_v_phys | lower | Morphometric SM50 was lower than values provided for SM50 based on a measure of physiological or functional maturity. |
| morph_v_phys | none | No comparison between morphometric SM50 and other maturity types was made. |
| morph_v_phys | same | Morphometric SM50 was roughly the same as values provided for SM50 based on a measure of physiological or functional maturity. |
| mult_models | complex | Not equivocally true or false; see comments for additional information. |
| mult_models | FALSE | FALSE |
| mult_models | TRUE | TRUE |
| novel_stats | complex | Not equivocally true or false; see comments for additional information. |
| novel_stats | FALSE | FALSE |
| novel_stats | TRUE | TRUE |
| reg_mention | complex | Not equivocally true or false; see comments for additional information. |
| reg_mention | FALSE | FALSE |
| reg_mention | TRUE | TRUE |
| sex | B | Estimates made for both males and females, but separately and possibly using different allometric variables, |
| sex | C | SM50 estimate made using combined measurements of the same allometric variables from both sexes |
| sex | F | Females only |
| sex | M | Males only |
| sex | NS | Not specified |
| spatial_var | complex | Not equivocally true or false; see comments for additional information. |
| spatial_var | FALSE | FALSE |
| spatial_var | TRUE | TRUE |
| success | complex | Not equivocally true or false; see comments for additional information. |
| success | FALSE | FALSE |
| success | TRUE | TRUE |
| time_var | complex | Not equivocally true or false; see comments for additional information. |
| time_var | FALSE | FALSE |
| time_var | TRUE | TRUE |
| f_ab_slope; m_claw_slope; f_ab_int; m_claw_int | inc | Increased at maturity |
| f_ab_slope; m_claw_slope; f_ab_int; m_claw_int | dec | Decreased at maturity |
| f_ab_slope; m_claw_slope; f_ab_int; m_claw_int | none | No significant change at maturity |
| f_ab_slope; m_claw_slope; f_ab_int; m_claw_int | NA | Not discussed or not applicable for the modeling approach used |

## Measurements

|  |  |
|----|----|
| **code** | **definition** |
| ca_w | Carapace width, not otherwise specified. |
| long_ca_w | Long carapace width: maximum carapace width including spines |
| short_ca_w | Short carapace width: maximum carapace width excluding spines. Measurements of "internal carapace width" are assumed to be of this type. |
| ca_len | Carapace length, not otherwise specified. |
| long_ca_len | Long carapace length: distance from the tips of the two frontal teeth to the extreme posterior margin of the carapace, excluding curvature of the carapace. |
| short_ca_len | Short carapace length: distance from the base of the two frontal teeth to the extreme posterior margin of the carapace, excluding curvature of the carapace. |
| fo_w | Fronto-orbital width: distance between the outer angles of the orbits. |
| f_w | Frontal width: distance across the portion of the carapace between but not including the orbital area. |
| ab_w | Abdomen width, not otherwise specified. |
| ab_w2 | Width of 2nd abdominal segment |
| ab_w3 | Width of 3rd abdominal segment |
| ab_w4 | Width of 4th abdominal segment |
| ab_w5 | Width of 5th abdominal segment |
| ab_w6 | Width of 6th abdominal segment |
| ab_w7 | Width of 7th abdominal segment |
| ab_len | Abdomen length. |
| bod_h | Body height (depth): Distance between the highest part of the dorsal metagastric region and a point along the ventral median line just anterior to the flexed abdomen. |
| cheliped_len | Cheliped length: Distance from the articulation of the coxa with the sternum to the most distal part of the propodus OR not otherwise specified. |
| cheliped_w | Cheliped width, not otherwise specified. |
| cp_len | Chela propodus (=manus) length. Distance from the tip of the propodus (sometimes tip of dactyl) to the articulation with the carpus. If not otherwise specified, "chela/claw length" is assumed to refer to this. |
| cp_w | Chela propodus width (breadth). If not otherwise specified, "chela/claw width" is assumed to refer to this. Includes measurements referring to chela palm width/breath. |
| cp_h | Chela propodus height (depth). Distance between the long dorsal spine and the base of the propodus. Includes variables described as chela palm height or depth. If not otherwise specified, "chela/claw height" assumed to refer to this. |
| ch_palm_len | Chela palm length. Diagonally across chela palm (as in Conan & Comeau, 1986) or not otherwise specified. |
| merus_len | Merus length, variously defined. Wallace (1949): "Measured on a diagonal from the most posterior dorsal point of articulation of merus and carpus to the most anterior dorsal margin of articulation between the merus and preceding segment," whereas Finney (1981) measured on a straight line, not diagonal. |
| merus_w | Merus width, variously defined. |
| leg_len | Leg length, variously defined. E.g., Kulmiye et al. (2006): from the tip of the dactyl to the proximal margin of ischium. |
| head_w | Head width |
| head_len | Head length |
| head_h | Head height |
| bod_len | Body length |
| ww | Wet weight |
| dw | Dry weight |

### Measurement Notes

1.  Prefixes: l\_ = left, r\_ = right, d\_ = dominant, m\_ = minor. pre\_ = pre-molt, post\_ = post-molt, o\_ = original, reg\_ = regenerated. Use dominant and minor instead of left/right where possible
2.  "Claw" is assumed to mean chela rather than the entire cheliped
3.  Variables should only be recorded if they are used to (attempt to) estimate size at maturity. For example, crab weight may be recorded for general growth modeling but should not be listed as a variable unless changes in the relationship between weight and a different variable were used to estimate size at maturity

## References {.unnumbered}
