---
bibliography: ../references.bib
---

# Relevance to valuable fisheries

The National Marine Fisheries Service prioritizes optimizing stock yields, preventing overfishing, and enhancing climate and economic resilience within the U.S. seafood and fishing sectors [@noaafisheries2022]. Achieving these goals will require ongoing scientific advancements to support adaptive fisheries management in the face of shifting ecosystem dynamics [@noaafisheries2024]. My research will greatly expand our ability to accurately and non-invasively estimate crustacean size at maturity. The results of this project will be directly applicable to the establishment of minimum landing sizes and the development of stock assessment models for dozens of U.S. fisheries. Here, I provide evidence for the utility of modeling morphometric maturity for the management of specific crustacean species that support economically valuable U.S. fisheries.

## Jonah crab

Scientific name: *Cancer borealis*

Selected publications related to morphometric maturity: [@lawrence2020; @lawrence2021; @olsen2020; @moriyasu2002]

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                                                                                                              | **Source**                                                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Better knowledge of the Jonah crab reproductive biology, particularly maturation rates (e.g., age-at-maturity) ... would be useful to gain greater insight into crab population dynamics and vulnerability to overfishing."\                                 | Jonah Crab Benchmark Stock Assessment and Peer Review Report, 2023                                                                                                                     |
| \                                                                                                                                                                                                                                                             |                                                                                                                                                                                        |
| Under *2.3.2: Size-at-Maturity*: "We recognize additional modeling approaches need to be developed to better stabilize these models and improve performance."                                                                                                 |                                                                                                                                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reproductive studies pertaining to male-female spawning size ratios, the possibility of successful spawning by physiologically mature but morphometrically immature male crabs, and potential for sperm limitations should be conducted                       | [Research Priorities and Recommendations to Support Interjurisdictional Fisheries Management: JONAH CRAB](https://asmfc.org/uploads/file/65cb97282024JonahCrab_ResearchPriorities.pdf) |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Research growth mechanisms for both sexes (e.g., potential for terminal molt, lack of growth associated with molting, high natural mortality for adults) to explain lack of exploitation signal (i.e., lack of size structure change) in available data sets. | [Research Priorities and Recommendations to Support Interjurisdictional Fisheries Management: JONAH CRAB](https://asmfc.org/uploads/file/65cb97282024JonahCrab_ResearchPriorities.pdf) |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## American lobster

Scientific name: *Homarus americanus*

Selected publications related to morphometric maturity: [@templeman1935; @waller2021; @émond2010; @little2005; @comeau2002; @landers2001; @conan2001]

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | **Source**                                                                                                                                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "The Review Panel found all aspects of growth were very high research priorities, e.g., ..., continued monitoring and study of changes in size at maturity due to its influence on growth"\                                                                                                                                                                                                                                                                                                                                                                                                                                                | [2020 American Lobster Benchmark Stock Assessment and Peer Review Report\                                                                                                                                                                                                                       |
| \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | \                                                                                                                                                                                                                                                                                               |
| Under *8.2 - Research Recommendations*\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | ](https://www.asmfc.org/uploads/file/5fb2c4a82020AmLobsterBenchmarkStockAssmt_PeerReviewReport.pdf)[Research Priorities and Recommendations to Support Interjurisdictional Fisheries Management: AMERICAN LOBSTER](https://asmfc.org/uploads/file/63ea7b2dResearchPriorities_AmLobster2020.pdf) |
| a. Maturity (Medium Priority) ... Future maturity work should focus on additional statistical areas with large landings contributions. Exploration of non‐invasive techniques to assess maturity are also desirable, allowing for more frequent and efficient updates to maturity estimates. Methods to allow for time‐varying maturity in the assessment model should also be explored, to better capture the influence of a changing environment on lobster population dynamics. Finally, it is extremely important for the newly updated maturity data to be applied towards updating the growth matrix underlying the assessment model |                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Up to date female size at maturity studies and accompanying biological measurements are necessary for future assessment and management efforts."\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | @waller2021                                                                                                                                                                                                                                                                                     |
| \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                 |
| "This work highlights the need to update historical maturity datasets as these measures of lobster development and growth are integral to evaluations of the size-based regulatory tools used in the management of the American lobster fishery."                                                                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "As the region continues to experience significant changes in the fishery and rates of warming, accurately characterizing size at maturity for female lobsters is key to assessing both reproductive potential and growth rates."\                                                                                                                                                                                                                                                                                                                                                                                                         | @ellertson2022                                                                                                                                                                                                                                                                                  |
| \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                 |
| "The spatial differences in size at maturity observed here reinforce the need to document potential changes in life history traits over the American lobster’s geographical range"                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Blue crab

Scientific name: *Callinectes sapidus*

Selected publications related to morphometric maturity: [@thienes2023; @olmi1983; @waugh2009; @olsen2016; @marchessaux2023; @newcombe1949]

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                                              | **Source**                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| "Evidence of a decreasing female size-at-maturity in the Chesapeake Bay could suggest that the productivity of the population is decreasing. CBSAC suggests prioritizing research studies that aim to address data gaps related to blue crab fecundity and population productivity to better understand trends in abundance." | Chesapeake Bay Stock Assessment Committee (CBSAC) Blue Crab Workshop Report, 2022             |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| "Knowledge of the species’ life history traits in Florida remains inadequate for a complete and accurate stock assessment. Specifically, much remains unknown about blue crab reproductive biology, seasonality of spawning, and recruitment patterns."                                                                       | @hart2021                                                                                     |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| "Research on the variability of reproductive parameters (e.g., maturity, fecundity and batch production) is a high priority."                                                                                                                                                                                                 | Stock Assessment of Blue Crab in Chesapeake Bay, 2011 (most recent complete stock assessment) |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+

## Snow crab

Scientific name: *Chionoecetes opilio*

Selected publications related to morphometric maturity: [@bakanev2023; @mullowney2021; @catlin2020; @divine2019; @dawe2012; @burmeister2010; @orensanz2007; @hébert2002; @mayrand1998; @claxton1994; @warren1994; @comeau1992] (extremely large body of research)

## Atlantic deep-sea red crab

Scientific name: *Chaceon quinquedens*

Selected publications related to morphometric maturity: [@stevens2016; @martínez-rivera2020; @haefner1977]

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                   | **Source**                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| "Studies to evaluate reproduction and sexual maturity are needed to estimate biological reference points and key parameters for fisheries management and stock assessment models."                                                                                                                 | @martínez-rivera2020                                                                                   |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| "Traditional reference points for the deep sea red crab stock are difficult to estimate due to lack of basic information."\                                                                                                                                                                        | [NEFSC Management Track Assessments, Spring 2023](https://repository.library.noaa.gov/view/noaa/55439) |
| \                                                                                                                                                                                                                                                                                                  |                                                                                                        |
| "The \[Peer Review\] Panel prioritized the collection of growth and natural mortality information... and simulation modeling to develop reference points appropriate for this species’ life history as the most important areas of research to move the assessment to a more analytical approach." |                                                                                                        |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| "Deep-sea red crab is a data-poor species with little known of its growth or longevity... There is scant information on biological parameters of red deepsea crab, such as size at maturity, fecundity, or timing of reproduction."                                                                | @stevens2016                                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+

## Dungeness crab

Scientific name: *Metacarcinus magister*

Selected publications related to morphometric maturity: [@wainwright1993; @worton2009; @collier1983; @butler1961]

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                   | **Source**  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| "Our study offers a first step toward evaluating the functional maturity and legal size limits of Dungeness crab, but until functional maturity can be defined in a competitive setting \[and\] a full functional maturity schedule is determined ... changing the size limit is not recommended." | @worton2009 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+

## King crab

Scientific name: *Paralithodes* spp. & *Lithodes* spp.

Selected publications related to morphometric maturity: [@wallace1949; @somerton1983; @filina2011; @stevens2014; @pengilly2002; @olson2018; @paul2000; @somerton1986; @sloan1985; @jewett1985; @somerton1981]

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                         | **Source**                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Size at maturity has not been determined specifcally for Pribilof Islands red king crab males."                                                                         | [2022 (triennial) assessment for Pribilof Islands red king crab](https://www.npfmc.org/about-the-council/plan-teams/bsai-crab-planning-team/)                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Specific research on St. Matthew Island blue king crab life history parameters is not available and therefore data are borrowed from other stocks/species."             | [2024 assessment for Saint Matthew Island blue king crab](https://meetings.npfmc.org/CommentReview/DownloadFile?p=9bd6e314-99e4-47b8-a7a4-e306c8c6a19e.pdf&fileName=SMBKC%20SAFE%202024.pdf)       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Size at maturity of NSRKC is highly uncertain."\                                                                                                                        | [2024 assessment for Norton Sound red king crab](https://meetings.npfmc.org/CommentReview/DownloadFile?p=277cb146-c63e-4bf4-a58d-d492a53fc68e.pdf&fileName=C1%20NSRKC%20SAFE.pdf)                  |
| Male crab size at maturity is listed as a "critical model assumption"                                                                                                    |                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Along with a lack of annual survey data, limited stock-specific life history stock information prevents development of a comprehensive length-based assessment model."\ | [2024 assessment for Aleutian Islands golden king crab](https://meetings.npfmc.org/CommentReview/DownloadFile?p=a74445e6-933f-462e-84b5-313a4eb6798d.pdf&fileName=C2%20AIGKC%20Safe%20Chapter.pdf) |
| Under *Research priorities:* Male size at maturity                                                                                                                       |                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Size at maturity has not been estimated for WAI male red king crab."                                                                                                    | [2023 (triennial) West Aleutian Islands red king crab](https://meetings.npfmc.org/CommentReview/DownloadFile?p=70a592e2-88a7-4aa4-9948-b31aecab1abb.pdf&fileName=WAIRKC_SAFE_2023.pdf)             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Stone crab

Scientific name: *Menippe* spp.

Selected publications related to morphometric maturity: [@zambrano2020; @crowley2018; @reeves2017; @gerhart2008; @bertini2007; @restrepo1989; @bert1986]

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                                                                                                                                                                                       | **Source**   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| "Transitioning to more sophisticated stock assessments, which would allow more effective fisheries management, will require detailed information on population biology, specifically, size at reproductive maturity."\                                                                                                                                                                                                                                                 | @crowley2018 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |              |
| "The development of accurate estimates of size at sexual maturity in stone crabs must use all available indicators of maturity and must include studies conducted throughout the range of the fished stock."                                                                                                                                                                                                                                                           |              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| "Assessment of the heavily exploited stone crab in Florida requires accurate descriptions of the reproductive biology and population dynamics of the stock."                                                                                                                                                                                                                                                                                                           | @crowley2019 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |              |
| Crowley et al. [-@crowley2019] developed an an age-structured model that utilized the new size at maturity information published in Crowley et al. [-@crowley2018]. The model estimates of spawning potential ratio (SPR) were sensitive to the assumed size at sexual maturity, demonstrated the sensitivity of estimated biological reference points to the input life-history parameters and highlighting the need for continued research into stone crab maturity. |              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+

## Tanner crab

Scientific name: *Chionoecetes bairdi*

Selected publications related to morphometric maturity: [@stevens1993; @paul1995; @otto2002; @stone2003; @fong2007; @murphy2021; @richar2022; @somerton1981a]

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Relevant research priorities**                                                                                                                                                                          | **Source**  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| "In many years our size at 50% maturity estimates were well below the regulation legal retention sizes... Further research into this issue, and careful monitoring in future years should be a priority." | @richar2022 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+

## Caribbean spiny lobster

Scientific name: *Panulirus argus*

Selected publications related to morphometric maturity: [@anderson2013; @atherley2021; @tewfik2020]

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Relevant research priorities**                                                                                                                                                                                                                                                                                                                                              | **Source**                                                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Under *7.1 Research Recommendations*: More basic biological studies to improve understanding of key life history processes\                                                                                                                                                                                                                                                   | [SEDAR 57 Stock Assessment Report, 2019](https://www.noaa.gov/sites/default/files/legacy/document/2021/Mar/ID406_Report_SEDAR57.pdf) (most recent completed stock assessment) |
| such as growth, length/age at maturity, fecundity, and their spatial variability.                                                                                                                                                                                                                                                                                             |                                                                                                                                                                               |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "Our study focused on size at sexual maturity in females, but based on our data, similar studies should be conducted on males." "Our findings underscore the importance of using locally derived reproductive data for regulatory decision making... Territories lacking recent data are advised to assess their *P. argus* populations using the techniques presented here." | @atherley2021                                                                                                                                                                 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## *Pandalus* shrimp

The genus *Pandalus* includes many species of shrimp that are economically valuable for the United States fishing industry. Commercial fishing occurs for ocean shrimp (*P. jordani*) off the coast of Washington, Oregon, and California, while spot shrimp (*P. platyceros*) are targeted throughout their geographic range from Southern California to the Aleutian Islands in Alaska [@levy2020]. Other shrimp of commercial and subsistence value in Alaska include the Alaskan pink shrimp (*P. eous*), the humpy shrimp (*P. goniurus*), the humpback shrimp, (*P. hypsinotus*), and the sidestripe shrimp (*P. dispar*). On the Atlantic coast, the northern shrimp (*P. borealis*) supported a large fishery in the Gulf of Maine for decades but is now extremely depleted and commercial fishing for northern shrimp is prohibited. Despite the fishing moratorium that has been in place since 2014, the most recent stock assessment update (December 2024) reported a continued decline in stock status, with all indices at all-time lows [@atlanticstatesmarinefisheriescommission2024].

*Pandalus* species are difficult to model using traditional stock assessment methods because they are protandric sequential hermaphrodites; i.e., they reproduce as males before changing sex to become female [@bergström2000]. Along with the size at which the sex transition occurs, their growth rate, recruitment dynamics, and natural mortality can be highly sensitive to changes in environmental conditions [@chang2021; @hansen2000; @perry2000; @hannah2011]. Rather than including a size at 50% maturity (SM50) parameter, current *P. borealis* stock assessment models include a parameter $L_{50_{sex}} (y)$, the length at which 50% of shrimp change sex to females in year *y* [@drouineau2012; @cao2017]. A statistical catch-at-length model model that includes environmental variables [@cao2017; @cao2017a] utilizing such a sex change function is now preferentially used for *P. borealis* management over catch-survey analysis (CSA) and Age Structured Assessment Program (ASAP) models used in previous analyses [@cadrin1999; @atlanticstatesmarinefisheriescommission2021; @atlanticstatesmarinefisheriescommission2018]. The notable plasticity of $L_{50_{sex}}$ in *Pandalus* means that it is useful as an indicator of population status; for example, comparing annual $L_{50_{sex}}$ values to established baselines is an important component of the management of the *P. platyceros* and *P. hypsinotus* fisheries in Southeast Alaska [@smith2020]. Because fecundity increases with size for *Pandalus* species, decreases in $L_{50_{sex}}$ result in decreased population fecundity, which can lead to lower recruitment and further reductions in population size [@smith2020].

Multiparous and primiparous females can be easily differentiated by sternal spines that are only present in females who have not previously spawned [@mccrary1971]. This criterion was used by Skúladóttir and Pétursson to calculate median length at maturity for *P. borealis* (an example of determining SM50 based on *functional* maturity) in the Denmark Strait, finding geographic variation in SM50 between three different areas in the waters around Iceland [@skúladóttir1998; @skúladóttir1999]. In conjunction with the general hermaphroditic structure of their life history, this means that morphometric maturity is not generally a highly relevant notion for *Pandalus* shrimps. However, morphometric analyses have been used to discriminate between populations of *P. borealis* from different Icelandic fjords [@jónsdóttir2016].

In summary, although size at maturity and morphometric analysis are separately important for *Pandalus*, size at morphometric maturity does not appear to be relevant for the U.S. fisheries for species within the genus.

## References {.unnumbered}
